<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-WorkerService1-1f68803f-6f01-4e0e-96ab-5e7dc8a3f1db</UserSecretsId>
		<UseWindowsForms>true</UseWindowsForms>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="appsettings.Development.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="SecuGen.FDxSDKPro.Windows">
			<HintPath>C:\Users\Tuinuane_CEO\Desktop\FDx_SDK_Pro_Windows_v4.3.1_J1.21\FDx SDK Pro for Windows v4.3.1\DotNETFramework\Bin\x64\SecuGen.FDxSDKPro.Windows.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<None Include="C:\Users\Tuinuane_CEO\Desktop\FDx_SDK_Pro_Windows_v4.3.1_J1.21\FDx SDK Pro for Windows v4.3.1\bin\x64\sgfplib.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="C:\Users\Tuinuane_CEO\Desktop\FDx_SDK_Pro_Windows_v4.3.1_J1.21\FDx SDK Pro for Windows v4.3.1\bin\x64\sgfdusdax64.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="C:\Users\Tuinuane_CEO\Desktop\FDx_SDK_Pro_Windows_v4.3.1_J1.21\FDx SDK Pro for Windows v4.3.1\bin\x64\sgfpamx.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="C:\Users\Tuinuane_CEO\Desktop\FDx_SDK_Pro_Windows_v4.3.1_J1.21\FDx SDK Pro for Windows v4.3.1\bin\x64\sgwsqlib.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="C:\Users\Tuinuane_CEO\Desktop\FDx_SDK_Pro_Windows_v4.3.1_J1.21\FDx SDK Pro for Windows v4.3.1\bin\x64\sgbledev.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>